version: "3.9"

services:
  database:
    image: postgres:14.2
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./docs/SCHEMA.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '${DB_PORT}:5432'
    networks:
      - appNetwork

  api:
    image: node:16
    env_file: .env
    build:
      context: .
    depends_on:
      - database
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    restart: unless-stopped
    networks:
      - appNetwork

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_USER}
    ports:
      - "${PG_PORT}:80"
    depends_on:
      - database
    networks:
      - appNetwork

networks:
  appNetwork:
    driver: bridge
